In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)
print(X)
print(y)

[[1.00e+00 1.00e+00 5.00e+02 1.00e+00]
 [1.00e+00 1.00e+00 7.00e+02 1.00e+00]
 [1.00e+00 2.00e+00 7.50e+02 2.00e+00]
 [1.00e+00 5.00e+00 6.00e+02 1.00e+00]
 [1.00e+00 3.00e+00 1.45e+03 2.00e+00]
 [1.00e+00 0.00e+00 8.00e+02 1.00e+00]
 [1.00e+00 5.00e+00 1.50e+03 3.00e+00]
 [1.00e+00 1.00e+01 2.00e+03 3.00e+00]
 [1.00e+00 1.00e+00 4.50e+02 1.00e+00]
 [1.00e+00 2.00e+00 1.00e+03 2.00e+00]]
[0. 0. 1. 0. 1. 0. 1. 0. 1. 1.]


In [3]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [4]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])
X_st

array([[ 1.        ,  1.        , -0.97958969,  1.        ],
       [ 1.        ,  1.        , -0.56713087,  1.        ],
       [ 1.        ,  2.        , -0.46401617,  2.        ],
       [ 1.        ,  5.        , -0.77336028,  1.        ],
       [ 1.        ,  3.        ,  0.97958969,  2.        ],
       [ 1.        ,  0.        , -0.36090146,  1.        ],
       [ 1.        ,  5.        ,  1.08270439,  3.        ],
       [ 1.        , 10.        ,  2.11385144,  3.        ],
       [ 1.        ,  1.        , -1.08270439,  1.        ],
       [ 1.        ,  2.        ,  0.05155735,  2.        ]])

1) *Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [5]:
def calc_logloss(y, y_pred):
    err = 0
    for i in range (len(y)):
        if y_pred[i] == 0:
            err -= ((1.0 - y[i]) * np.log(1.0 - y_pred[i]))
        elif y_pred[i] == 1:
            err -= (y[i] * np.log(y_pred[i]))
        else:
            err -= (y[i] * np.log(y_pred[i]) + (1.0 - y[i]) * np.log(1.0 - y_pred[i]))/len(y)
        #print(err)
    return err 

Проверяем будет ли функция считать ошибку если предсказанное значение является 0 или 1:

In [6]:
np.log(0.5)

-0.6931471805599453

In [7]:
y1 = np.array([1, 0])
y_pred1 = np.array([0.5, 0])
calc_logloss(y1, y_pred1)

0.34657359027997264

In [8]:
y1 = np.array([1, 0])
y_pred1 = np.array([1, 0.2])
calc_logloss(y1, y_pred1)

0.11157177565710485

In [9]:
y1 = np.array([1, 0])
y_pred1 = np.array([0.9, 0.5])
calc_logloss(y1, y_pred1)

0.39925384810888576

2) Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [10]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [11]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

Было:

In [12]:
W = eval_model(X_st, y, iterations=500, eta=1e-4)

0 [ 0.49667621 -0.13840939  0.6476858   1.52297324] 1.1785958344356264
50 [ 0.494784   -0.14564801  0.6475462   1.52014828] 1.1657985749255426
100 [ 0.49290109 -0.15285535  0.64740132  1.51733474] 1.1531112685708471
150 [ 0.49102761 -0.16003088  0.64725118  1.51453281] 1.1405352753305018
200 [ 0.48916364 -0.16717404  0.64709581  1.51174267] 1.1280719326917485
250 [ 0.48730929 -0.17428428  0.64693524  1.50896452] 1.1157225565960733
300 [ 0.48546465 -0.18136107  0.64676951  1.50619853] 1.103488442622439
350 [ 0.48362982 -0.18840385  0.64659868  1.5034449 ] 1.0913708674192037
400 [ 0.48180488 -0.19541206  0.64642281  1.50070383] 1.0793710903721336
450 [ 0.47998993 -0.20238516  0.64624195  1.49797551] 1.0674903554915993


Стало:

In [13]:
W = eval_model(X_st, y, iterations=1100, eta=1)

0 [ 0.11732727 -1.58914029  0.62030812  0.95688359] 1.1785958344356264
110 [-2.89131483 -1.08039003  0.31785452  3.41865542] 0.3690668430326905
220 [-4.69112005 -0.99764135 -0.42358672  4.54612843] 0.31759440936813244
330 [-5.99002891 -1.05302872 -0.88774001  5.46085515] 0.2924487122942722
440 [-7.03260607 -1.11249033 -1.2407543   6.23267867] 0.2759053132264223
550 [-7.92366684 -1.17070488 -1.53310732  6.91171368] 0.2636495410461249
660 [-8.71618637 -1.22692684 -1.78744473  7.52706504] 0.25385953687853297
770 [-9.4396611  -1.28111376 -2.01586954  8.09592938] 0.24564531750884724
880 [-10.11178116  -1.33339111  -2.22544939   8.62905489] 0.23852176183512466
990 [-10.7438102   -1.3839122   -2.42059783   9.13350732] 0.23220113622857758


3) Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [14]:
def calc_pred_proba (W, X):
    y_pred_proba = sigmoid(np.dot(X,W))
    return y_pred_proba 

In [15]:
calc_pred_proba (W, X_st)

array([0.3518314 , 0.15650524, 0.99802391, 0.0010299 , 0.73791188,
       0.31242323, 0.99945375, 0.08837061, 0.41517018, 0.99248136])

4) Создайте функцию calc_pred, возвращающую предсказанный класс. На вход подаётся W, который уже посчитан функцией eval_model, и X, на выходе — массив y_pred.

In [16]:
def calc_pred (W, X):
    y_pred = [1 if i > 0.5 else 0 for i in sigmoid(np.dot(X,W))]
    return y_pred

In [17]:
calc_pred(W, X_st)

[0, 0, 1, 0, 1, 0, 1, 0, 0, 1]

In [18]:
np.dot(X_st, W)

array([-0.61099875, -1.6844642 ,  6.22465485, -6.87726021,  1.03514361,
       -0.78881474,  7.51188047, -2.33369406, -0.34263239,  4.88282304])